### ISSUE TITLE
Can not run DITA-OT on database resources

### ISSUE THREAD

**Issue by mgaerber** [axxepta/project-argon#16]

**Comment by raducoravu** [comment]
The issue when running DITA publishing from Oxygen, right?
I made some changes for Oxygen 18 (Spring next year) which would allow you to keep using the options storage API for the user/password and this API to be accessible when your URL handler plugin is called in the publishing process. Would you be willing to test your integration with an Oxygen 18 nightly build that I could provide for you?

**Comment by mgaerber** [comment]
Access to options works (tested with 18.1), and most importantly, setting a DITA OT Scenario to
fix.external.refs.com.oxygenxml =true on Parameters tab
-Djava.protocol.handler.pkgs=de.axxepta.oxygen.customprotocol.ArgonProtocolHandler as JVM arg on Advanced tab
now correctly uses our protocol handler and successfully tranforms with DITA OT !

**Comment by raducoravu** [comment]
Strange, the publishing should have worked even without setting the fix.external and the protocol handler. When Oxygen detects that a DITA Map located on a remote server is published, it should automatically use its already installed protocol handler also for the DITA OT transformation.
