### ISSUE TITLE
Improve versioning

### ISSUE THREAD

**Issue by mgaerber** [axxepta/project-argon#17]
* Every save = new Revision
* New version = initiated by user action
* One history DB per source DB
* Always save complete document

**Comment by MarkusWb** [comment]
Version and initial/previous file name in processing instruction

**Comment by MarkusWb** [comment]
Try to use Oxygen file diff for version diff

**Comment by raducoravu** [comment]
We don't quite have API on the diff side of things. What exactly would you need? To visually launch the Diff Files tool or some kind of API which compares XML files and saves differences in a certain format?

**Comment by MarkusWb** [comment]
We would like to give the user a possibility to compare different 
revisions of a file, ideally by passing them to the Diff Files tool--so, 
launching the tool, not saving the differences.

Am 04.12.2015 um 15:22 schrieb Radu Coravu:

**Comment by raducoravu** [comment]
We'll probably have some specific API to open the Diff Files tool with two specified URLs in 18.0. I will try to increase the issue's priority.
If you you want this sooner and do not mind a hack, we have an exposed not obfuscated class in our main JAR library called "ro.sync.diff.ui.DiffFilesMainFrame".
This class originally contained a singleton static access method called:

>   /**
>    * Get singleton instance.
>    * @return The singleton instance.
>    */
>   public static DiffFilesMainFrame getInstance()

but it is obfuscated in the compiled class, the obfuscator changed its original name. You could gain access to the obfuscated method using Java reflection, searching for a static method in the class which returns that precise object type.
Then after you invoke the method and have the singleton object, you should again search for an obfuscated method which is not static and receives two URLs as parameters. That method was originally named "show". Invoking the method on the two URLs should show the diff files main frame.

**Comment by raducoravu** [comment]
Oxygen 18.0 was released a couple of weeks ago and it should have the API:

        ro.sync.exml.workspace.api.standalone.StandalonePluginWorkspace.openDiffFilesApplication(URL, URL)
