### ISSUE TITLE
Insert/edit PIs without changing editor mode

### ISSUE THREAD

**Issue by mgaerber** [axxepta/project-argon#28]
Using _AuthorDocumentController_ one can manipulate nodes: 

       `try{
                //
                final AuthorDocumentController adc = authorAccess.getDocumentController();
                int startOffset = adc.getAuthorDocumentNode().getRootElement().getStartOffset();
                
                AuthorDocumentFragment frag = adc.createNewDocumentFragmentInContext("<?history version=\"\"?>", startOffset + 1);
                adc.insertFragment(startOffset, frag);
                
            } catch (AuthorOperationException e) {
                e.printStackTrace();
            }

            // find nodes
            //AuthorNode[] nodes = adc.findNodesByXPath("/processing-instruction('history')", true, true, true);

**Comment by raducoravu** [comment]
I noticed that when saving the document, it switches to Text and then to Author. Indeed you should use the Author API to make changes to it. 
So +1 from me.

**Comment by mgaerber** [comment]
Currently, the PI also drives the next revision number. This should be handled by the database query.

New proposed workflow on document save:
 * if no PI is present and option for versioning is set, add initial PI
 * if PI is present, first save to DB and query for a new PI, then replace in Editor

I think it is okay when the Editor replaces the PI because re-loading the whole document could have other effects - especially if we try to play nice with other components that might want to access the document

**Comment by mgaerber** [comment]
After putting some more thoughts into this, I am in favour of skipping PIs for versioning alltogether.

Instead, I think we should maintain metadata files. I am sure we will have to maintain several meta infos soon and just adding more PIs does not seem to be a good idea.

**Comment by mgaerber** [comment]
Separate metadata files are in the works, so closing this thread, bye bye PI
