### ISSUE TITLE
React on 'return' key for dialogs 

### ISSUE THREAD

**Issue by mgaerber** [axxepta/project-argon#31]
e.g. 
* Add database -> enter name -> hit enter
* Options dialog (database connection) should react on hitting enter as well

**Comment by raducoravu** [comment]
Is there an issue for F5 to perform the "Refresh" in the Argon DB Connection view?

**Comment by mgaerber** [comment]
#7 was meant for things like F5 on the TreeView. Should add this by Swing API or should we hook into some Oxygen API?

**Comment by raducoravu** [comment]
You can use the swing way of adding key bindings using the tree component's action and input map.

**Comment by raducoravu** [comment]
:+1: noticed also the "Rename" dialog does not close on ENTER pressed

**Comment by MarkusWb** [comment]
hope I got them all where it applies...
