### ISSUE TITLE
Treeview: Drag/Drop files

### ISSUE THREAD

**Issue by mgaerber** [axxepta/project-argon#6]

**Comment by mgaerber** [comment]
New customer request: Drop files from Tree onto Editor window (for opening)

**Comment by raducoravu** [comment]
If the dragged node from the tree supports this flavor:

     new DataFlavor("text/uri-list;class=java.lang.String", null)

and you drop it in Oxygen on our side the code requests the string from the handler:

     String listOfURIs = (String)transferable.getTransferData(new DataFlavor("text/uri-list;class=java.lang.String", null));

then checks if there are line breaks in the string and splits the string to create a list of URLs. Then Oxygen decides whether it should open the URLs or create links to them. From what I remember, by default it will open them.

**Comment by MarkusWb** [comment]
drop files on tree, copy and move (inside databases) in tree, drag to editor area to open
